#!/bin/sh
#------------------------------------------
#      Centos6 asp.net InstallScript
#      copyright https://github.com/cjy37
#      email: rocky.cn@foxmail.com
#------------------------------------------

function showMenu()
{
	clear
	echo
	echo "--------------------------------------------------------------"
	echo "|      Centos6 Install Helper                                |"
	echo "|      copyright https://github.com/cjy37                    |"
	echo "--------------------------------------------------------------"
	echo "|      a. Install Web Server + MySQL [d,e,g,h,k,l]           |"
	echo "|      b. Install Web Server   [d,e,g,k,l]                   |"
	echo "|      c. Install MySQL    [d,h,l]                           |"
	echo "|      d. Install Libs     [Public Libs]                     |"
	echo "|      e. Install mono                                       |"
	echo "|      g. Install jexus v5                                   |"
	echo "|      h. Install mysql v5.5                                 |"
	echo "|      i. Install memcached                                  |"
	echo "|      j. Install nginx                                      |"
	echo "|      k. Install haproxy                                    |"
	echo "|      l. Install Redis                                      |"
	echo "|      m. Install CutyCapt                                   |"
	echo "|      n. Install GtkSharp                                   |"
	echo "|      x. Exit                                               |"
	echo "--------------------------------------------------------------"
	echo
	return 0
}

function setupOs7Epel()
{
	echo "Install Centos7_64bit EPEL repository"
	rpm -ivh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-2.noarch.rpm
	rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
	yum -y install yum-priorities
	
	return 0
}

function setupOs6Epel()
{
	echo "Install Centos6_64bit EPEL repository"
	rpm -ivh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
	rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-6
	yum -y install yum-priorities
	
	return 0
}

function setupOs5Epel()
{
	echo "Install Centos5_64bit EPEL repository"
	rpm -ivh http://dl.fedoraproject.org/pub/epel/5/x86_64/epel-release-5-4.noarch.rpm
	rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-5
	yum -y install yum-priorities
	
	return 0
}

function setupLibs()
{
	vers=`cat /etc/redhat-release | awk -F'release' '{print $2}' | awk -F'.' '{print $1}' | awk -F' ' '{print $1}'`
	if [ "$vers" = "7" ]; then
		setupOs7Epel
	elif [ "$vers" = "6" ]; then
		setupOs6Epel
	elif [ "$vers" = "5" ]; then
		setupOs5Epel
	fi

	yum -y update
	yum -y groupinstall "Development Tools"

	echo "Install the public Libs"
	echo "------------------------------------"

	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /wwwroot/htdocs/www ]; then
	  mkdir -pv /wwwroot/htdocs/www
	fi

	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi

	yum -y install gcc gcc-c++ autoconf libjpeg libjpeg-devel libpng libpng-devel freetype freetype-devel libxml2 libxml2-devel zlib zlib-devel glibc glibc-devel glib2 glib2-devel bzip2 bzip2-devel ncurses ncurses-devel curl curl-devel e2fsprogs e2fsprogs-devel krb5 krb5-devel libidn libidn-devel openssl openssl-devel openldap openldap-devel nss_ldap openldap-clients openldap-servers patch make jpackage-utils build-essential bzip bison pkgconfig glib-devel httpd-devel libX11-devel fontconfig pango-devel ruby ruby-rdoc gtkhtml38-devel wget gettext gcc-g77 automake fiex* libmcrypt* libtool-ltdl-devel* pcre* cmake mhash* libevent libevent-devel gif* libtiff* libjpeg* libpng* libx11* libiconv mcrypt Nginx haproxy

	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/raw/master/conf.zip
	if [ -f conf.zip ]; then
			unzip -o conf.zip
	fi

	echo "install libiconv"
	echo "------------------------------------"
	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/raw/master/libiconv-1.13.1.tar.gz
	if [ -f libiconv-1.13.1.tar.gz ]; then
	  tar xvf libiconv-1.13.1.tar.gz
	  cd libiconv-1.13.1
	  ./configure --prefix=/usr
	  make && make install
	  ldconfig
	fi

	echo "install mcrypt"
	echo "------------------------------------"
	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/raw/master/mcrypt-2.6.8.tar.gz
	if [ -f mcrypt-2.6.8.tar.gz ]; then
	  tar xvf mcrypt-2.6.8.tar.gz
	  cd mcrypt-2.6.8
	  ./configure --prefix=/usr
	  make && make install
	  ldconfig
	fi

	return 0
}

function setupLibgdiplus()
{
	echo "install libgdiplus"
	echo "------------------------------------"
	cd /tmp/downloads
	wget -c http://download.mono-project.com/sources/libgdiplus/libgdiplus-2.10.9.tar.bz2
	if [ -f libgdiplus-2.10.9.tar.bz2 ]; then
		tar -jxvf libgdiplus-2.10.9.tar.bz2
		cd libgdiplus-2.10.9
		./configure --prefix=/usr
		make && make install
	fi
	ldconfig
	ldconfig -p |grep libgdiplus

	return 0
}

function setupMemcached()
{
	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi

	echo "install memcached"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/raw/master/memcached-1.4.6.tar.gz
	if [ -f memcached-1.4.6.tar.gz ]; then
	  tar xvf memcached-1.4.6.tar.gz
	  cd memcached-1.4.6
	  ./configure --prefix=/usr/local/webserver/memcached
	  make && make install
	  ldconfig
	  cp -r -f /tmp/downloads/conf/memcached /etc/init.d/memcached
	  chmod 755 /etc/init.d/memcached
	  chkconfig --add memcached
	  chkconfig memcached on
	  service memcached start
	fi
	return 0
}

function setupMono()
{
	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /wwwroot/htdocs/www ]; then
	  mkdir -pv /wwwroot/htdocs/www
	fi
	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi
	
	echo "Install mono v3.6+"
	echo "------------------------------------"

	rpm --import xamarin.gpg
	yum-config-manager --add-repo http://download.mono-project.com/repo/centos/
	
	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/raw/master/aspx-info.tar.gz
	wget -c http://download.mono-project.com/sources/mono/mono-3.10.0.tar.bz2
	if [ -f mono-3.10.0.tar.bz2 ]; then
	  tar -jvxf mono-3.10.0.tar.bz2
	  cd mono-3.10.0
	  ./configure --prefix=/usr
	  sed -i 's/#define HAVE_LOCALCHARSET_H 1/#define HAVE_LOCALCHARSET_H 0/g' eglib/config.h
	  make && make install
	  ldconfig
	fi
	echo "Install mono completed. info:"
	mono -V

  return 0
}

function setupMysql()
{
	echo "install Mysql"
	echo "------------------------------------"
	
	echo '# MariaDB 10.1 CentOS repository list - created 2014-10-17 07:52 UTC
# http://mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.1/centos6-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1' > /etc/yum.repos.d/MariaDB.repo

	yum -y install MariaDB-server MariaDB-client MariaDB-devel
	chkconfig --level 2345 mysqld on
	service mysqld start
	
	mysql -V
	
	echo "Mysql: Please Ender user(root) password"
	read -e PWD
	mysqladmin -uroot password "$PWD"
	return 0
}

function setupNginx()
{

	echo "install nginx"
	echo "------------------------------------"

	echo '[nginx]
name=nginx repo
baseurl=http://nginx.org/packages/centos/$releasever/$basearch/
gpgcheck=0
enabled=1' > /etc/yum.repos.d/nginx.repo
	yum -y install nginx
	chkconfig --level 2345 nginx on
	service nginx start
	nginx -v
	
	return 0
}

function setupHaproxy()
{
	echo "install haproxy"
	echo "------------------------------------"

	if [ ! -d /usr/local/webserver/haproxy ]; then
	  echo "/usr/local/webserver/haproxy/sbin/haproxy -f /usr/local/webserver/haproxy/conf/haproxy.cfg &" >> /etc/rc.local
	fi
	if [ ! -d /usr/local/webserver/haproxy ]; then
	  mkdir -pv /usr/local/webserver/haproxy
	fi
	if [ ! -d /usr/local/webserver/haproxy/conf ]; then
	  mkdir -pv /usr/local/webserver/haproxy/conf
	fi

	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/raw/master/haproxy-1.4.22.tar.gz
	if [ -f haproxy-1.4.22.tar.gz ]; then
		tar zxvf haproxy-1.4.22.tar.gz
		cd haproxy-1.4.22
		make TARGET=linux26 PREFIX=/usr/local/webserver/haproxy
		make install PREFIX=/usr/local/webserver/haproxy
		ldconfig
		cp -r -f /tmp/downloads/conf/haproxy.cfg /usr/local/webserver/haproxy/conf/haproxy.cfg
	fi
	return 0
}

function setupRedis()
{
	echo "install Redis"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/raw/master/redis-2.4.4.tar.gz
	if [ -f redis-2.4.4.tar.gz ]; then
	  tar zxvf redis-2.4.4.tar.gz
	  cd redis-2.4.4
	  make
	  make PREFIX=/usr/local install
	  ldconfig
	  mkdir /etc/redis
	  cp -r -f /tmp/downloads/conf/redis.conf /etc/redis/redis.conf

	  mkdir  /var/lib/redis
		cp -r -f /tmp/downloads/conf/redis-server.sh /etc/init.d/redis
		# cp -r -f redis-server.sh /etc/init.d/redis
		chmod +x /etc/init.d/redis
		chkconfig --add redis
		chkconfig --level 2345 redis on
		/etc/init.d/redis start
	fi
	return 0
}

function setupJws()
{
	if [ ! -d /wwwroot/htdocs/www ]; then
	  mkdir -pv /wwwroot/htdocs/www
	fi
	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi
	if [ ! -d /usr/jexus ]; then
	  mkdir -pv /usr/jexus
	  echo  "/usr/jexus/jws start" >> /etc/rc.local
	fi

	echo "install jexus"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c http://www.linuxdot.net/down/jexus-5.6.3.tar.gz
	if [ -f jexus-5.6.3.tar.gz ]; then
	  tar -xf jexus-5.6.3.tar.gz
	  cd jexus-5.6.3
	  ./install
	  chmod +x /usr/jexus/*
	  
	  sed -i 's/root=\/ \/var\/www\/default/root=\/ \/wwwroot\/htdocs\/www/g' /usr/jexus/siteconf/default

	fi
	
	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/blob/master/aspx-info.tar.gz?raw=true
	if [ -f aspx-info.tar.gz ]; then
	  tar xvf aspx-info.tar.gz
	  cd aspx-info
	  cp -r -f index.aspx /wwwroot/htdocs/www/index.aspx
	  echo "Web Root Path: /wwwroot/htdocs/www/"
	  echo "If you need change it. Please vim the Jexus config file(/usr/jexus/siteconf/*)"
	fi
	
	/usr/jexus/jws start
	/usr/jexus/jws -V
	echo "Jexus install to path: /usr/jexus/"
	echo "Please vim the Jexus config file (/usr/jexus/jws.conf and /usr/jexus/siteconf/*)"
	  
	return 0
}

function setupGtkSharp()
{
	cd /tmp/downloads
	#=========================================================
	echo "/opt/gtk/lib" > /etc/ld.so.conf.d/gtk.conf
	export LD_LIBRARY_PATH=/opt/gtk/lib:$LD_LIBRARY_PATH
	export PKG_CONFIG_PATH=/usr/lib/pkgconfig
	export PKG_CONFIG_PATH=/opt/gtk/lib/pkgconfig:$PKG_CONFIG_PATH
	ldconfig
	#=========================================================
	wget https://github.com/cjy37/linux-asp.net-installScript/raw/master/glib-2.13.7.tar.bz2
	tar xvfj  glib-2.13.7.tar.bz2
	cd glib-2.13.7
	./configure --prefix=/opt/gtk --with-libiconv=gnu && make && make install
	ldconfig
	cd ..

	wget https://github.com/cjy37/linux-asp.net-installScript/raw/master/atk-1.19.6.tar.bz2
	tar xvfj atk-1.19.6.tar.bz2
	cd atk-1.19.6
	./configure --prefix=/opt/gtk && make && make install
	cd ..

	wget https://github.com/cjy37/linux-asp.net-installScript/raw/master/pixman-0.22.2.tar.gz
	tar xvfz pixman-0.22.2.tar.gz
	cd pixman-0.22.2
	./configure --prefix=/opt/gtk && make && make install
	cd ..

	wget https://github.com/cjy37/linux-asp.net-installScript/raw/master/cairo-1.8.10.tar.gz
	tar xvfz cairo-1.8.10.tar.gz
	cd cairo-1.8.10
	./configure --prefix=/opt/gtk && make && make install
	cd ..

	wget https://github.com/cjy37/linux-asp.net-installScript/raw/master/pango-1.17.3.tar.bz2
	tar xvfj pango-1.17.3.tar.bz2
	cd pango-1.17.3
	./configure --prefix=/opt/gtk && make && make install
	ldconfig
	cd ..

	wget https://github.com/cjy37/linux-asp.net-installScript/raw/master/gtk+-2.12.0.tar.bz2
	tar xvfj gtk+-2.12.0.tar.bz2
	cd gtk+-2.12.0
	./configure --prefix=/opt/gtk --with-x --without-libjasper && make && make install
	ldconfig
	cd ..

	wget https://github.com/cjy37/linux-asp.net-installScript/raw/master/gtk-sharp-2.12.11.tar.bz2
	tar xvfj gtk-sharp-2.12.11.tar.bz2
	cd gtk-sharp-2.12.11
	./configure --prefix=/usr && make && make install
	cd ..

	return 0
}

function setupCutyCapt()
{
	cd /tmp
	wget http://ftp.riken.go.jp/Linux/atrpms/el5-i386/atrpms/testing/qt44-4.4.3-10_4.el5.i386.rpm
	wget http://ftp.riken.go.jp/Linux/atrpms/el5-i386/atrpms/testing/qt44-x11-4.4.3-10_4.el5.i386.rpm
	wget http://ftp.riken.go.jp/Linux/atrpms/el5-i386/atrpms/testing/qt44-devel-4.4.3-10_4.el5.i386.rpm

	yum -y install libmng libXi-devel libXinerama-devel libGLU-devel libICE-devel libSM-devel libXcursor-devel libXfixes-devel libXrandr-devel libXt-devel

	rpm -ivh qt44-4.4.3-10* qt44-x11-4.4.3-10* qt44-devel-4.4.3-10*

	ldconfig
	echo "export QTDIR=/usr/lib/qt44" >> /etc/profile
	echo "export QTLIB=/usr/lib/qt44/lib" >> /etc/profile
	echo "export QTINC=/usr/lib/qt44/include" >> /etc/profile
	echo "export LD_LIBRARY_PATH=$QTDIR/lib:$LD_LIBRARY_PATH" >> /etc/profile
	echo "export PATH=$QTDIR/bin:$PATH" >> /etc/profile
	source /etc/profile

	svn co https://cutycapt.svn.sourceforge.net/svnroot/cutycapt
	mv cutycapt/CutyCapt /usr/local/CutyCapt
	cd /usr/local/CutyCapt
	/usr/lib/qt44/bin/qmake
	make

	wget http://www.flexthinker.com/wp-content/uploads/2009/11/xvfb-run.sh.txt
	mv ./xvfb-run.sh.txt /usr/local/CutyCapt/xvfb-run.sh
	chmod u+x /usr/local/CutyCapt/xvfb-run.sh

	yum install fonts-chinese

	#/usr/local/CutyCapt/xvfb-run.sh --server-args="-screen 0, 1024x768x24" /usr/local/CutyCapt/CutyCapt --url=http://www.163.com --out=163.jpg

	return 0
}

function selectCmd()
{
	alias cp='cp'
	showMenu
	echo "Please select a serial number for installation"
	echo "When your manual installation, Please install the [d] first:"
	echo "[f][g] be dependent on [e]:"
	read -n 1 M
	echo

	if [ "$M" = "x" ]; then
		exit 1
	elif [ "$M" = "a" ]; then
		 echo "Installing ALL... [d,e,g,h,k,l]"
		 echo "------------------------------------"
		 setupLibs
		 setupLibgdiplus
		 setupMono
		 setupJws
		 setupMysql
		 setupHaproxy
		 setupRedis
	elif [ "$M" = "b" ]; then
		 echo "Installing Web Server ... [d,e,g,k,l]"
		 echo "------------------------------------"
		 setupLibs
		 setupLibgdiplus
		 setupMono
		 setupJws
		 setupHaproxy
		 setupRedis
	elif [ "$M" = "c" ]; then
		 echo "Installing MySQL ... [d,h,l]"
		 echo "------------------------------------"
		 setupLibs
		 setupMysql
		 setupRedis
	elif [ "$M" = "d" ]; then
		 setupLibs
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "e" ]; then
     setupLibgdiplus
     read -n 1 -p "Press <Enter> to continue..."
		 setupMono
     read -n 1 -p "Press <Enter> to continue..."
	#elif [ "$M" = "f" ]; then
	#	 setupXsp
    # read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "g" ]; then
		 setupJws
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "h" ]; then
		 setupMysql
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "i" ]; then
		 setupMemcached
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "j" ]; then
		 setupNginx
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "k" ]; then
		 setupHaproxy
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "l" ]; then
		 setupRedis
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "m" ]; then
		 setupCutyCapt
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "n" ]; then
		 setupGtkSharp
     read -n 1 -p "Press <Enter> to continue..."
	else
		 echo "Select Error!"
     read -n 1 -p "Press <Enter> to continue..."
	fi

	selectCmd
	return 0
}
cd /tmp
selectCmd
