#!/bin/sh
#------------------------------------------
#      Fedora19/20 asp.net InstallScript
#      copyright https://github.com/cjy37
#      email: rocky.cn@foxmail.com
#------------------------------------------

function showMenu()
{
	read -n 1 -p "Press [Any Key] to setup public libs. [Ctrl + C] to Cancel."
	setupLibs
	clear
	echo
	echo "--------------------------------------------------------------"
	echo "|      Fedora19/20 Install Helper                            |"
	echo "|      copyright https://github.com/cjy37                    |"
	echo "--------------------------------------------------------------"
	echo "|      a. Install ALL                                        |"
	echo "|      b. Install Web Server (linux mono mysql jexus)[c,d]   |"
	echo "|      c. Install Mono & Jexus (Asp.Net Web Server)          |"
	echo "|      d. Install Mysql (MariaDB-10)                         |"
	echo "|      e. Install Haproxy                                    |"
	echo "|      f. Install Redis                                      |"
	echo "|      g. Install Node.js                                    |"
	echo "|      h. Install MongoDB                                    |"
	echo "|      i. Install Nginx                                      |"
	echo "|      x. Exit                                               |"
	echo "--------------------------------------------------------------"
	echo
	return 0
}


function selectCmd()
{
	alias cp='cp'
	showMenu
	echo "Please select a serial number for installation [a-x]:"
	read -n 1 M
	echo

	if [ "$M" = "x" ]; then
		exit 1
		
	elif [ "$M" = "a" ]; then
		echo "Installing ALL..."
		echo "------------------------------------"
		setupMono && setupJws && setupMysql && setupHaproxy && setupRedis && setupNodejs && setupNginx && setupMongodb
		read -n 1 -p "Press <Enter> to continue..."
		
	elif [ "$M" = "b" ]; then
		echo "Installing Web Server ... [c,d]"
		echo "------------------------------------"
		setupMono && setupJws && setupMysql
		read -n 1 -p "Press <Enter> to continue..."
		
	elif [ "$M" = "c" ]; then
		setupMono && setupJws
		read -n 1 -p "Press <Enter> to continue..."

	elif [ "$M" = "d" ]; then
		setupMysql
		read -n 1 -p "Press <Enter> to continue..."

	elif [ "$M" = "e" ]; then
		setupHaproxy
		read -n 1 -p "Press <Enter> to continue..."

	elif [ "$M" = "f" ]; then
		setupRedis
		read -n 1 -p "Press <Enter> to continue..."
		
	elif [ "$M" = "g" ]; then
		setupNodejs
		read -n 1 -p "Press <Enter> to continue..."
		
	elif [ "$M" = "h" ]; then
		setupMongodb
		read -n 1 -p "Press <Enter> to continue..."
		
	elif [ "$M" = "i" ]; then
		setupNginx
		read -n 1 -p "Press <Enter> to continue..."

	else
		echo "Select Error!"
		read -n 1 -p "Press <Enter> to continue..."
	fi

	selectCmd
	return 0
}

function setupNodejs()
{
	echo "install Node.js"
	echo "------------------------------------"
	sudo yum -y install nodejs
	echo "Install nodejs completed. info:"
	node -v

	sudo echo "sudo npm install forever|mqtt|websocket|websocket-server|socket.io to '/wwwroot/node_mqtt'"

	sudo npm install forever -g
	sudo npm install mqtt -g
	sudo npm install websocket -g
	sudo npm install websocket-server -g
	sudo npm install socket.io@0.9 -g
	sudo npm install log4js -g
	sudo npm install pm2 -g --unsafe-perm
	
	return 0
}

function setupMongodb()
{
	echo "install Mongodb"
	echo "------------------------------------"
	sudo yum -y install mongodb mongodb-server
	echo "Install mongodb completed. info:"
	mongod --version
	
	return 0
}


function setupLibs()
{
	sudo yum -y update
	sudo yum -y groupinstall "Development Tools"
	echo "Install the public Libs"
	echo "------------------------------------"
	sudo yum -y install libjpeg libjpeg-devel libpng libpng-devel curl curl-devel wget gif* libtiff* libjpeg* 
	return 0
}
function setupMono()
{
	cd /tmp
	wget http://download.mono-project.com/repo/xamarin.gpg
	sudo rpm --import xamarin.gpg
	sudo yum-config-manager --add-repo http://download.mono-project.com/repo/centos/
	sudo yum -y install mono-complete
	echo "Install mono completed. info:"
	mono -V

	return 0
}
function setupMysql()
{
	echo "install mysql"
	echo "------------------------------------"
	
	vers=`cat /etc/redhat-release | awk  '{print $3}' | awk -F'.' '{print $1}'`
	
	if [ "$vers" = "19" ]; then
	
		echo '# MariaDB 10.1 Fedora repository list - created 2014-10-17 08:04 UTC
# http://mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.1/fedora19-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1' | sudo tee /etc/yum.repos.d/MariaDB.repo

	elif [ "$vers" = "20" ]; then
	
		echo '# MariaDB 10.1 Fedora repository list - created 2014-10-17 08:06 UTC
# http://mariadb.org/mariadb/repositories/
[mariadb]
name = MariaDB
baseurl = http://yum.mariadb.org/10.1/fedora20-amd64
gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
gpgcheck=1' | sudo tee /etc/yum.repos.d/MariaDB.repo

	fi
	
	sudo yum -y install MariaDB-server MariaDB-client MariaDB-devel
	sudo chkconfig --level 2345 mysql on
	sudo service mysql start
	
	mysql -V
	
	echo "Mysql: Please Ender user(root) password"
	read -e PWD
	sudo mysqladmin -uroot password "$PWD"
	return 0
}
function setupNginx()
{
	echo "install nginx"
	echo "------------------------------------"
	
	sudo yum -y install nginx
	nginx -v
	
	return 0
}
function setupHaproxy()
{
	echo "install haproxy"
	echo "------------------------------------"
	sudo yum -y install haproxy
	return 0
}
function setupRedis()
{
	echo "install Redis"
	echo "------------------------------------"
	sudo yum -y install redis
	return 0
}
function setupJws()
{
	if [ ! -d /wwwroot/htdocs/www ]; then
	  mkdir -pv /wwwroot/htdocs/www
	fi
	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi
	if [ ! -d /usr/jexus ]; then
	  mkdir -pv /usr/jexus
	  echo  "/usr/jexus/jws start" >> /etc/rc.d/rc.local
	fi

	echo "install jexus"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c http://www.linuxdot.net/down/jexus-5.6.3.tar.gz
	if [ -f jexus-5.6.3.tar.gz ]; then
	  tar -xf jexus-5.6.3.tar.gz
	  cd jexus-5.6.3
	  sudo ./install
	  sudo chmod +x /usr/jexus/*
	  
	  sudo sed -i 's/root=\/ \/var\/www\/default/root=\/ \/wwwroot\/htdocs\/www/g' /usr/jexus/siteconf/default

	fi
		
	cd /tmp/downloads
	wget -c https://github.com/cjy37/linux-asp.net-installScript/blob/master/aspx-info.tar.gz?raw=true
	if [ -f aspx-info.tar.gz ]; then
	  tar xvf aspx-info.tar.gz
	  cd aspx-info
	  sudo cp -r -f index.aspx /wwwroot/htdocs/www/index.aspx
	  echo "Web Root Path: /wwwroot/htdocs/www/"
	  echo "If you need change it. Please vim the Jexus config file(/usr/jexus/siteconf/*)"
	fi
	
	sudo /usr/jexus/jws start
	sudo /usr/jexus/jws -V
	echo "Jexus install to path: /usr/jexus/"
	echo "Please vim the Jexus config file (/usr/jexus/jws.conf and /usr/jexus/siteconf/*)"
	  
	return 0
}

cd /tmp
selectCmd
