#!/bin/bash
#------------------------------------------
#      Ubuntu asp.net InstallScript
#      copyright https://github.com/cjy37
#      email: rocky.cn@foxmail.com
#------------------------------------------

function setupLibs()
{
	sudo apt-get update -y
        sudo apt-get upgrade -y

	echo "Install the public Libs"
	echo "------------------------------------"

	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /wwwroot/htdocs/www ]; then
	  mkdir -pv /wwwroot/htdocs/www
	fi

	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi



	#if [ -f yum.zip ]; then
	#		unzip -o yum.zip
	#fi



	#cp -r -f /tmp/downloads/conf/yum.conf /etc/yum.conf
	#cp -r -f /tmp/downloads/yum /tmp

	cd /tmp
	sudo apt-get install -y chkconfig
	sudo apt-get install -y build-essential
	sudo apt-get install -y automake autoconf
	sudo apt-get install -y bison gettext libtool libglib2.0-dev libfreetype6-dev libfontconfig-dev
	sudo apt-get install -y libgif-dev libtiff4-dev libpng12-dev libexif-dev libx11-dev libxft-dev libjpeg-dev
	sudo apt-get install mono-runtime
	
	cd /tmp/downloads
	wget -c http://flex-ui-libs.googlecode.com/files/conf.zip
	if [ -f conf.zip ]; then
			unzip -o conf.zip
	fi

	echo "install libiconv"
	echo "------------------------------------"
	cd /tmp/downloads
	wget -c http://flex-ui-libs.googlecode.com/files/libiconv-1.13.1.tar.gz
	if [ -f libiconv-1.13.1.tar.gz ]; then
	  tar xvf libiconv-1.13.1.tar.gz
	  cd libiconv-1.13.1
	  ./configure --prefix=/usr
	  make && sudo make install
	  ldconfig
	fi

	echo "install mcrypt"
	echo "------------------------------------"
	cd /tmp/downloads
	wget -c http://flex-ui-libs.googlecode.com/files/mcrypt-2.6.8.tar.gz
	if [ -f mcrypt-2.6.8.tar.gz ]; then
	  tar xvf mcrypt-2.6.8.tar.gz
	  cd mcrypt-2.6.8
	  ./configure --prefix=/usr
	  make && sudo make install
	  ldconfig
	fi
	setupLibgdiplus
	
	return 0
}

function setupLibgdiplus()
{
	echo "install libgdiplus"
	echo "------------------------------------"
	cd /tmp/downloads
	wget http://download.mono-project.com/sources/libgdiplus/libgdiplus-2.10.tar.bz2
	
	if [ -f libgdiplus-2.10.tar.bz2 ]; then
		tar -jxvf libgdiplus-2.10.tar.bz2
		cd libgdiplus-2.10
		./configure --prefix=/usr
		make && sudo make install
	fi
	ldconfig
	ldconfig -p |grep libgdiplus

	return 0
}

function setupMemcached()
{
	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi

	echo "install memcached"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c http://flex-ui-libs.googlecode.com/files/memcached-1.4.6.tar.gz
	if [ -f memcached-1.4.6.tar.gz ]; then
	  tar xvf memcached-1.4.6.tar.gz
	  cd memcached-1.4.6
	  ./configure --prefix=/usr/local/webserver/memcached
	  make && sudo make install
	  ldconfig
	  cp -r -f /tmp/downloads/conf/memcached /etc/init.d/memcached
	  chmod 755 /etc/init.d/memcached
	  chkconfig --add memcached
	  chkconfig memcached on
	  service memcached start
	fi
	return 0
}

function setupMono()
{
	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /wwwroot/htdocs/www ]; then
	  mkdir -pv /wwwroot/htdocs/www
	fi
	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi

	echo "install mono"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c http://flex-ui-libs.googlecode.com/files/aspx-info.tar.gz
	wget -c http://download.mono-project.com/sources/mono/mono-3.0.12.tar.bz2
	if [ -f mono-3.0.12.tar.bz2 ]; then
	  tar -jvxf mono-3.0.12.tar.bz2
	  cd mono-3.0.12
	  ./configure --prefix=/usr
	  # cp -r -f /tmp/downloads/conf/config.h eglib/config.h
	  make && sudo make install
	  ldconfig
	fi

	cd /tmp/downloads
	if [ -f aspx-info.tar.gz ]; then
	  tar xvf aspx-info.tar.gz
	  cd aspx-info
	  cp -r -f index.aspx /wwwroot/htdocs/www/index.aspx
	fi

  return 0
}

function setupMysql()
{
	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi
	if [ ! -d /usr/local/webserver/mysql ]; then
	  mkdir -pv /usr/local/webserver/mysql
	  mkdir -pv /usr/local/webserver/mysql/etc
	  mkdir -pv /usr/local/webserver/mysql/bin
	fi
	if [ ! -d /wwwroot/mysql ]; then
	  mkdir -pv /wwwroot/mysql

	  groupadd -g 3306 mysql
	  useradd -u 3306 -g mysql -M -s /sbin/nologin mysql
	  chown -R mysql:mysql /wwwroot/mysql/
	fi

	echo "install mysql"
	echo "------------------------------------"

	#apt-install mysql
	sudo apt-get install -y python-software-properties
	sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 0xcbcb082a1bb943db
	sudo add-apt-repository 'deb http://mirror.stshosting.co.uk/mariadb/repo/5.5/ubuntu precise main'
	sudo apt-get update -y
	sudo apt-get install -y libmysqlclient18=5.5.32+maria-1~precise mysql-common=5.5.32+maria-1~precise
	sudo apt-get install -y mariadb-server mariadb-client
	
	return 0
}

function setupNginx()
{
	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /wwwroot/htdocs/www ]; then
	  mkdir -pv /wwwroot/htdocs/www
	fi

	#/wwwroot/logs
	if [ ! -d /wwwroot/logs ]; then
	  mkdir -pv /wwwroot/logs
	fi

	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi
	if [ ! -d /usr/local/webserver/nginx ]; then

	  mkdir -pv /usr/local/webserver/nginx
	fi

	echo "install nginx"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c http://flex-ui-libs.googlecode.com/files/nginx-1.1.1.tar.gz
	if [ -f nginx-1.1.1.tar.gz ]; then
	  tar xvf nginx-1.1.1.tar.gz
	  cd nginx-1.1.1
	  ./configure --prefix=/usr/local/webserver/nginx --with-http_stub_status_module --with-http_ssl_module
	  make && sudo make install
	  ldconfig

    cp -r -f /tmp/downloads/conf/fastcgi_params /usr/local/webserver/nginx/conf/fastcgi_params
    cp -r -f /tmp/downloads/conf/nginx.conf /usr/local/webserver/nginx/conf/nginx.conf

		cp -r -f /tmp/downloads/conf/nginx /etc/init.d/nginx
	  chmod +x /etc/init.d/nginx
		chkconfig --add nginx
		chkconfig --level 2345 nginx on
		/etc/init.d/nginx start

	fi
	return 0
}

function setupHaproxy()
{
	echo "install haproxy"
	echo "------------------------------------"

	if [ ! -d /usr/local/webserver/haproxy ]; then
	  echo "/usr/local/webserver/haproxy/sbin/haproxy -f /usr/local/webserver/haproxy/conf/haproxy.cfg &" >> /etc/rc.local
	fi
	if [ ! -d /usr/local/webserver/haproxy ]; then
	  mkdir -pv /usr/local/webserver/haproxy
	fi
	if [ ! -d /usr/local/webserver/haproxy/conf ]; then
	  mkdir -pv /usr/local/webserver/haproxy/conf
	fi

	cd /tmp/downloads
	sudo apt-get install haproxy
	return 0
}

function setupRedis()
{
	echo "install Redis"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c http://flex-ui-libs.googlecode.com/files/redis-2.4.4.tar.gz
	if [ -f redis-2.4.4.tar.gz ]; then
	  tar zxvf redis-2.4.4.tar.gz
	  cd redis-2.4.4
	  make
	  sudo make install PREFIX=/usr/local
	  ldconfig
	  mkdir /etc/redis
	  cp -r -f /tmp/downloads/conf/redis.conf /etc/redis/redis.conf

	  mkdir  /var/lib/redis
		cp -r -f /tmp/downloads/conf/redis-server.sh /etc/init.d/redis
		# cp -r -f redis-server.sh /etc/init.d/redis
		chmod +x /etc/init.d/redis
		chkconfig --add redis
		chkconfig --level 2345 redis on
		/etc/init.d/redis start
	fi
	return 0
}

function setupJws()
{
	if [ ! -d /usr/local/webserver ]; then
	  mkdir -pv /usr/local/webserver
	fi
	if [ ! -d /wwwroot/htdocs/www ]; then
	  mkdir -pv /wwwroot/htdocs/www
	fi
	if [ ! -d /tmp/downloads ]; then
	  mkdir -pv /tmp/downloads
	fi
	if [ ! -d /usr/local/webserver/jexus ]; then
	  mkdir -pv /usr/local/webserver/jexus
	  echo  "/usr/local/webserver/jexus/jws start" >> /etc/rc.local
	fi

	echo "install jexus5.3.1"
	echo "------------------------------------"

	cd /tmp/downloads
	wget -c http://www.linuxdot.net/down/jexus-5.4.3.1.tar.gz
	if [ -f jexus-5.4.3.1.tar.gz ]; then
	  tar -xf jexus-5.4.3.1.tar.gz
	  cd jexus-5.4.3.1
	  sudo ./install # /usr/local/webserver/jexus
	  /usr/jexus/jws start
	fi
	return 0
}



function showMenu()
{
	clear
	echo
	echo "--------------------------------------------------------------"
	echo "|      CentOS Install Helper                                 |"
	echo "|      copyright https://github.com/cjy37                    |"
	echo "--------------------------------------------------------------"
	echo "|      a. Install Web Server + MySQL [d,e,g,h,k,l]           |"
	echo "|      b. Install Web Server   [d,e,g,k,l]                   |"
	echo "|      c. Install MySQL    [d,h,l]                           |"
	echo "|      d. Install Libs     [Public Libs]                     |"
	echo "|      e. Install mono                                       |"
	echo "|      g. Install jexus v5                                   |"
	echo "|      h. Install mysql v5.5                                 |"
	echo "|      i. Install memcached                                  |"
	echo "|      j. Install nginx                                      |"
	echo "|      k. Install haproxy                                    |"
	echo "|      l. Install Redis                                      |"
	echo "|      x. Exit                                               |"
	echo "-------------------------------------------------------------"
	echo
	return 0
}

function selectCmd()
{
	alias cp='cp'
	showMenu
	echo "Please select a serial number for installation"
	echo "When your manual installation, Please install the [d] first:"
	echo "[f][g] be dependent on [e]:"
	read -n 1 M
	echo

	if [ "$M" = "x" ]; then
		exit 1
	elif [ "$M" = "a" ]; then
		 echo "Installing ALL... [d,e,g,h,k,l]"
		 echo "------------------------------------"
		 setupLibs
		 setupMono
		 setupJws
		 setupMysql
		 setupHaproxy
		 setupRedis
	elif [ "$M" = "b" ]; then
		 echo "Installing Web Server ... [d,e,g,k,l]"
		 echo "------------------------------------"
		 setupLibs
		 setupMono
		 setupJws
		 setupHaproxy
		 setupRedis
	elif [ "$M" = "c" ]; then
		 echo "Installing MySQL ... [d,h,l]"
		 echo "------------------------------------"
		 setupLibs
		 setupMysql
		 setupRedis
	elif [ "$M" = "d" ]; then
		 setupLibs
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "e" ]; then
		 setupMono
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "g" ]; then
		 setupJws
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "h" ]; then
		 setupMysql
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "i" ]; then
		 setupMemcached
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "j" ]; then
		 setupNginx
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "k" ]; then
		 setupHaproxy
     read -n 1 -p "Press <Enter> to continue..."
	elif [ "$M" = "l" ]; then
		 setupRedis
     read -n 1 -p "Press <Enter> to continue..."
	else
		 echo "Select Error!"
     read -n 1 -p "Press <Enter> to continue..."
	fi

	selectCmd
	return 0
}


cd /tmp
selectCmd




